# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/oledTest_12_02/Zybo-Z7-Master.xdc

# Block Designs: bd/ReactionSpeedTester/ReactionSpeedTester.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester || ORIG_REF_NAME==ReactionSpeedTester} -quiet] -quiet

# IP: bd/ReactionSpeedTester/ip/ReactionSpeedTester_processing_system7_0_0/ReactionSpeedTester_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester_processing_system7_0_0 || ORIG_REF_NAME==ReactionSpeedTester_processing_system7_0_0} -quiet] -quiet

# IP: bd/ReactionSpeedTester/ip/ReactionSpeedTester_oledControl_0_0/ReactionSpeedTester_oledControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester_oledControl_0_0 || ORIG_REF_NAME==ReactionSpeedTester_oledControl_0_0} -quiet] -quiet

# IP: bd/ReactionSpeedTester/ip/ReactionSpeedTester_ps7_0_axi_periph_0/ReactionSpeedTester_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester_ps7_0_axi_periph_0 || ORIG_REF_NAME==ReactionSpeedTester_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ReactionSpeedTester/ip/ReactionSpeedTester_rst_ps7_0_50M_0/ReactionSpeedTester_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester_rst_ps7_0_50M_0 || ORIG_REF_NAME==ReactionSpeedTester_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ReactionSpeedTester/ip/ReactionSpeedTester_xbar_0/ReactionSpeedTester_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester_xbar_0 || ORIG_REF_NAME==ReactionSpeedTester_xbar_0} -quiet] -quiet

# IP: bd/ReactionSpeedTester/ip/ReactionSpeedTester_myKEYPAD2_0_0/ReactionSpeedTester_myKEYPAD2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester_myKEYPAD2_0_0 || ORIG_REF_NAME==ReactionSpeedTester_myKEYPAD2_0_0} -quiet] -quiet

# IP: bd/ReactionSpeedTester/ip/ReactionSpeedTester_Timer_0_6/ReactionSpeedTester_Timer_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester_Timer_0_6 || ORIG_REF_NAME==ReactionSpeedTester_Timer_0_6} -quiet] -quiet

# IP: bd/ReactionSpeedTester/ip/ReactionSpeedTester_auto_pc_0/ReactionSpeedTester_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReactionSpeedTester_auto_pc_0 || ORIG_REF_NAME==ReactionSpeedTester_auto_pc_0} -quiet] -quiet

# XDC: bd/ReactionSpeedTester/ReactionSpeedTester_ooc.xdc
