# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/backup/ReactionSpeedTester_12_9/ReactionSpeedTester.srcs/sources_1/bd/ReactionSpeedTester/ip/ReactionSpeedTester_xbar_0/ReactionSpeedTester_xbar_0.xci
# IP: The module: 'ReactionSpeedTester_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/backup/ReactionSpeedTester_12_9/ReactionSpeedTester.srcs/sources_1/bd/ReactionSpeedTester/ip/ReactionSpeedTester_xbar_0/ReactionSpeedTester_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ReactionSpeedTester_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/backup/ReactionSpeedTester_12_9/ReactionSpeedTester.srcs/sources_1/bd/ReactionSpeedTester/ip/ReactionSpeedTester_xbar_0/ReactionSpeedTester_xbar_0.xci
# IP: The module: 'ReactionSpeedTester_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/backup/ReactionSpeedTester_12_9/ReactionSpeedTester.srcs/sources_1/bd/ReactionSpeedTester/ip/ReactionSpeedTester_xbar_0/ReactionSpeedTester_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ReactionSpeedTester_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
